import os
os.system("git pull")
os.system("clear")
#print("")
#print("")
#print("\033[1;92m		THIS TOOL IS DELETED.\n	SO NO MORE UPDATE WILL COME FROM THIS TOOL")
#print("")
#print("")
os.system("chmod 777 MAGI")
os.system("./MAGI")
