import os
os.system("clear")
os.system("clear")
os.system("xdg-open https://chat.whatsapp.com/F5zQSelUr7M7VFDTC3BrZw")
os.system("clear")
os.system("git pull")
#print("")
#print("")
#print("\033[1;92m		TOOL IS UNDER MAINTENANCE \n		  WAIT FOR NEXT UPDATE")
#print("")
#print("")
os.system("chmod 777 MAGI-2")
os.system("./MAGI-2")
